square/certigo

.travis.yml
README.md

r: @christodenny @worldwise001 @mcpherrinm @alokmenghrajani 
Add travis-ci build file, update readme. Fixes #20.

Add travis-ci build file

---

main.go

r: @christodenny 
Removes guessing code from `getCerts` and splits it out into a separate function, also adds supports for guessing more formats. This way each function has a single concern.

Guess more formats, clean up guessing code

---

jceks/AUTHORS

r: @worldwise001 @alokmenghrajani @mcpherrinm @christodenny 
Add AUTHORS file to jceks package

Add AUTHORS file to jceks package

---

README.md
jceks/jceks.go
jceks/jceks_test.go
main.go

r: @christodenny @mcpherrinm @alokmenghrajani. Fixes #39.

Support stdin, add examples to readme

---

display.go
main.go

Algorithm color highlighting

---

display.go

r: @christodenny 
Show basic constraints

Show basic constraints

---

display.go

Show lints/warnings when dumping certificates. Fixes #13, #14 and #15.

Show lints/warnings when dumping certificates

---

display.go

Show key usage and extended key usage. Fixes #10.

Show key usage and extended key usage

---

display.go

Fix version warning format string

Fix version warning format string

---

display.go

Add more warnings

---

README.md
output_1.svg
output_2.svg
output_3.svg

cheating with SVG.
Preview: https://github.com/square/certigo/blob/bdcb9b8fae71a370e4b6475a82976ce9ae09b2fb/README.md

Add some colors.

---

main.go

@christodenny @alokmenghrajani @mcpherrinm

Couple of fixes

---

main.go

r: @alokmenghrajani @mcpherrinm @alokmenghrajani 
Support streaming print of PEM blocks

Support streaming print of PEM blocks

---

display.go
main.go

r: @christodenny @alokmenghrajani @csstaub

Add a command to connect to a TLS server and print its presented certs

---

examples/example_3_ffafad.svg

r: @mcpherrinm 
Update the TLS connect example to show certigo built-in command instead of s_client.

Update connect example

---

main.go

r: @alokmenghrajani @mcpherrinm @christodenny 
Skip non-certificate PEM blocks

Skip non-certificate PEM blocks

---

main.go

r: @alokmenghrajani @mcpherrinm @christodenny 
Add command for converting any input to PEM blocks

Add command for converting any input to PEM blocks

---

README.md
examples/example_1_245953.svg
examples/example_2_d848d5.svg
examples/example_3_ffafad.svg

r: @alokmenghrajani @christodenny @mcpherrinm 
Update README to add usage output

Update README to add usage output

---

main.go
verify.go

r: @mcpherrinm @alokmenghrajani @christodenny 
Add verify debug output to connect command.
Examples:
Examples are from connecting to squareup.com, expired.badssl.com, wrong.host.badssl.com.

Add verify debug output to connect command

---

display.go
verify.go

@alokmenghrajani @mcpherrinm @christodenny 
Improve formatting, show if certificate is self-signed

Improve formatting, show if self-signed

---

display.go
main.go

r: @christodenny @mcpherrinm @alokmenghrajani 
Clean up cert extraction logic: merges the logic for dumping certs and converting to PEM blocks into one function. Use callbacks instead of channels, much nicer.

Clean up cert extraction logic

---

README.md
display.go
examples/example_2.svg
examples/example_3.svg
main.go

r: @mcpherrinm @alokmenghrajani @christodenny 
Depends on #79.

Add --pem flag for dump/connect, remove pem command

---

README.md

Mention homebrew in readme.

---

.travis.yml
display.go
verify.go

Support Go 1.5, don't depend on x509.SignatureAlgorithm.String()

Support Go 1.5, don't depend on x509.SignatureAlgorithm.String()

---

cert_encoder.go
display.go
encoder.go
main.go
verify.go

@worldwise001 I took the liberty of rebasing your JSON branch on master and adding support for JSON output to the verify command.

Rebased JSON

---

lib/certs.go
lib/display.go
lib/encoder.go
main.go
verify.go

Factor out useful functions into library

Factor out useful functions into library

---

main.go

Support for client certificates in certigo connect

Support for client certificates in certigo connect

---

.travis.yml
lib/certs.go

Return error instead of printing to stderr in lib. Oversight from when this was factored out.

Return error instead of printing to stderr in lib

---

jceks/jceks.go

Don't panic in the JCEKS library

---

main.go

Add a newline for better errors

---

main.go

Remove unused tlsConfigForConnect function (was copied to starttls package)

Remove unused tlsConfigForConnect function

---

main.go
starttls/ftp.go
starttls/starttls.go

Implement AUTH TLS for FTP servers. Tested with vsftpd.

Implement AUTH TLS for FTP servers

---

lib/display.go
lib/encoder.go
tests/dump-cert-chain-to-text.t

Show OCSP servers and issuing certificate URL info in verbose mode

Show OCSP servers and issuing certificate URL info in verbose mode

---

.travis.yml
lib/display.go
lib/encoder.go
tests/dump-mozilla-cacert-bundle.t
tests/dump-name-constraints-to-text.t

Support new name constraint fields in crypto/x509

Support new name constraint fields in crypto/x509

---

main.go
starttls/ftp.go
starttls/starttls.go

Pure-FTPd seems broken without this.

Improve FTP & starttls protocol handling 

---

lib/ocsp.go
lib/verify.go

Cleanup printing code, print revocation reason, print indicator if OCSP was stapled.

Print revocation reason & staple status

---

lib/ocsp.go

* Add HTTP timeouts (don't block forever)
* Add retries (up to 3, in case we see failures)
* Fix GET request building (drop escaping)
* Return issuer from fetch to properly verify signatures

Improve reliability of OCSP checks

---

main.go

Unverified chains will cause a non-zero exit code.
Fixes #188

Verify certificate chain in connect

---

cli/cli.go
go.mod
go.sum

Prep for 1.12 release

---

cli/cli.go

Fixes https://github.com/square/certigo/issues/233

Allow `certigo -h`

---

go.mod
go.sum

Fix https://github.com/square/certigo/security/dependabot/1

Upgrade yaml.v3 version

---

cli/cli.go

Bump version to prepare for release.

Update to 1.16

---

cli/cli_test.go
jceks/utils_test.go
lib/certs.go
starttls/ldap/ldap.go
starttls/mysql/utils.go
starttls/psql/ssl.go

ioutil is deprecated. Move the replacements.

Remove ioutil
