- .gitignore
- .travis.yml
- Makefile
- README.md
- glide.lock
- glide.yaml
r: @christodenny @alokmenghrajani @mcpherrinm @worldwise001 
Setup glide for vendoring/pinning dependencies to specific versions. Also add makefile. Fixes #27.
> Use glide for vendoring

- display.go
- main.go
GetCerts now returns an array of alias strings along with certs,
the array contains empty strings if not jceks. DisplayCerts
now takes in an alias string along with the cert and only prints
it if non empty.
@csstaub ptal
> Added support to output alias info for jceks certs.

- display.go
r: @christodenny 
Put serial at the top of the output, because that's what most other tools do. Also removes the conditional around the serial number, since it will always be present.
> Put serial on top of output

- glide.lock
- glide.yaml
- main.go
Plays nicer with: `./certigo dump foo.jceks | grep ...`
Note: does't yet work with `cat foo.jceks | ./certigo dump`.
> Improve password input handling

- display.go
- main.go
r: @christodenny @alokmenghrajani @mcpherrinm
Support multiple file arguments, making it possible to run e.g. `certigo dump test-certs/*.crt`.
> Support multiple file arguments

- output_1.svg
- output_2.svg
- output_3.svg
@alokmenghrajani @mcpherrinm @christodenny 
Slightly better/more consistent spacing at the end of SVG examples. Third example had a bit too much margin at the bottom, first two examples had no margin at the bottom.
> Slightly better spacing in SVG files

- main.go
r: @christodenny @alokmenghrajani @mcpherrinm
Display PKCS12 friendly name for certs. The `crypto/pkcs12` package puts safe bag attrs in the PEM header, so we can read it from there.
> Display PKCS12 friendly name for certs

- build
Build file used by formula file for homebrew installation.
Basically just a copy of similar file from certstrap.
@csstaub @alokmenghrajani @mcpherrinm ptal
> Added build file

- main.go
r: @mcpherrinm 
Dumping from file prints newlines in between certs for readability, this changes the connect command to do the same.
> Print newline after cert dump from connect

- README.md
- main.go
- pkcs7/pkcs7.go
r: @worldwise001 @mcpherrinm @stfinney @christodenny 
Changes:
* Support PKCS7 envelopes in DER streams (previously only worked via PEM input)
* Support multiple certificates in DER streams (instead of just one)
> Support PKCS7 envelopes, multiple certificates in DER streams

- README.md
- examples/example_2.svg
- main.go
- tests/export-jceks.t
- tests/export-pkcs12.t
@mcpherrinm @worldwise001 @stfinney 
Not all software supports extra headers. Notably, OpenSSL will be sad
and refuse to parse the PEM block. Fixes #89.
> Strip headers from PEM output blocks

- main.go
- verify.go
Add separate verify command to validate certificates from a file/stdin.
```
$ certigo connect --pem squareup.com:443 > example-chain.crt
$ ./certigo verify --name squareup.com < example-chain.crt
Server certificates appear to be valid (found 2 chains):
[0] www.squareup.com
=> Entrust Certification Authority - L1M
=> Entrust Root Certification Authority - G2 [self-signed]
[1] www.squareup.com
=> Entrust Certification Authority - L1M
=> Entrust Root Certification Authority - G2
=> Entrust Root Certification Authority [self-signed] [SHA1-RSA]
$ ./certigo verify --name google.com < example-chain.crt
Failed to verify certificate chain:
x509: certificate is valid for www.squareup.com, squareup.com, account.squareup.com, mkt.com, www.mkt.com, market.squareup.com, gosq.com, www.gosq.com, gosq.co, …
```
> Add separate verify command to validate certificates

- main.go
- starttls/starttls.go
Uses net/smtp, which is apparently frozen, but conveniently already has a TLSConnectionState() function.
> Add SMTP STARTTLS support 

- main.go
- verify.go
This is pulled in as a dependency of fatih/color, but the way we were printing output wasn't automatically compatible with Windows.
This makes our colored output explicitly go through a colorable stdout handle.
> Add support for coloured output on windows

- README.md
Use output from --help-long in README, instead of just --help. Has more info on flags and such.
> Use --help-long output in readme

- main.go
- verify.go
* Print a message before verified chains to make output a bit more readable
* Strip newlines from errors so we don't have double-newlines (some errors end with \n, others don't)
> Nicer output for verified chains

- lib/display.go
- lib/oids.go
- main.go
- tests/dump-cert-chain-to-text.t
- tests/dump-jceks-to-pem.t
- tests/dump-leaf-to-not-verbose.t
- tests/dump-leaf-to-text.t
- tests/dump-pkcs12-to-pem.t
- tests/dump-small-key-to-text.t
This gets rid of a lot of information that I think I don't care about most of the time, in my experience debugging TLS.  We print not before / not after, subject, issuer, name constraints, SANS, and warnings.
there's a new --verbose flag that prints the old output.
Sample output: 
```
./certigo connect squareup.com:443
** TLS Connection **
Version: TLS 1.2
Cipher Suite: ECDHE_RSA key exchange, AES_128_GCM_SHA256 cipher
** CERTIFICATE 1 **
Valid: 2016-06-10 22:14 UTC to 2017-07-31 20:45 UTC
Subject: C=US, ST=California, L=San Francisco, , , O=Square, Inc., CN=www.squareup.com
Issuer: C=US, O=Entrust, Inc., OU=See www.entrust.net/legal-terms, OU=(c) 2014 Entrust, Inc. - for authorized use only, CN=Entrust Certification Authority - L1M
Alternate DNS Names:
www.squareup.com
squareup.com …
```
> Make text certs shorter, existing text output now has a --verbose flag

- main.go
- starttls/ftp.go
- starttls/ldap/conn.go
- starttls/starttls.go
Support connect timeouts! Except for SMTP, because net/smtp doesn't support timeouts/deadlines. Could submit a patch to upstream, or fork.
> Support connect timeouts

- README.md
JKS doesn't actually work.
I'll look into why later, and can re-add it when fixed.
> Remove JKS from readme

- main.go
- starttls/starttls.go
Right now, this hardcodes "certigo" (instead of the default "localhost")
Next up, make this configurable.
> smtp hello

- lib/display.go
- lib/encoder.go
- lib/tls.go
- main.go
- starttls/starttls.go
- verify.go
Example output:
```
** TLS Connection **
Version: TLS 1.2
Cipher Suite: ECDHE_RSA key exchange, AES_128_GCM_SHA256 cipher
Server has requested a client certificate:
Acceptable issuers:
C=US, ST=CA, O=ghostunnel, OU=root
Supported Signature Schemes:
RSA-PKCS1WithSHA256
ECDSAWithP256AndSHA256
RSA-PKCS1WithSHA384
ECDSAWithP384AndSHA384
RSA-PKCS1WithSHA1
ECDSAWithSHA1
** CERTIFICATE 1 **
Valid: 2016-06-10 21:12 UTC to 2019-03-07 21:12 UTC
Subject: CN=server
Issuer: C=US, ST=CA, O=ghostunnel, OU=root
Alternate DNS Names:
localhost
Alternate IP Addresses:
127.0.0.1, ::1
Found 1 valid certificate chain(s):
[0] CN=server
=> C=US, ST=CA, O=ghostunnel, OU=root [self-signed]
```
Note: this will only reliably work if you compile with Go 1.8.1, due to a bug in Go 1.8.0 where the GetClientCertificate …
> Add support for showing requested client certificate info

- lib/certs.go
- main.go
- pkcs7/pkcs7.go
Better error handling in certigo dump command.
Previous:
```
$ certigo dump < invalid-data
$
```
Updated:
```
$ certigo dump < invalid-data
error parsing block: asn1: structure error: sequence tag mismatch
warning: no certificates found in input
$
```
> Better error handling in certigo dump command

- lib/oids.go
Surprisingly, this appears to be actually used in the wild:
http://www.alvestrand.no/objectid/0.9.2342.19200300.100.1.1.html
> Add user id OID in lib/oids

- lib/encoder.go
- lib/tls.go
Better strings for TLS signature schemes
> Better strings for TLS signature schemes

- main.go
- starttls/starttls.go
If otherwise unspecified, default to port 443.
If a starttls protocol is given, use a protocol-specific default.
So now "certigo connect squareup.com" works.
> Add protocol-specific default ports

- lib/certs.go
Better error message for library users. Mentioning the format flag doesn't make sense for people who call this as a library (e.g. ghostunnel).
> Better error message for library users

- main.go
Certigo doesn't have too many options, so the long help is a reasonble default.
> Default to using the "long" help format

- lib/ocsp.go
- lib/verify.go
- main.go
Also moved verify.go and ocsp.go into lib to tidy things up.
This reduces a bunch of copy-paste code.
Todo, truststore password handling.
> Support more formats for CA trust stores.

- .travis.yml
- CONTRIBUTING.md
- README.md
- readme: removed reference to Glide and mentioned Go modules
- contributing: language tweaks & updated link to CLA
- CI: remove glide dependency, since we don't need it and Go 1.11
ignores vendored dirs when using `./...` argument to go tools.
> Update README and CONTRIBUTING

- lib/oids.go
I found TP-LINK routers submit some kind of logging to
n-devs.tplinkcloud.com:50443 and the CA that signed the certificate
for that domain had DCs in its subject
With this change we now get:
Issuer:
DC=cn, DC=com, DC=tp-link, CN=TP-LINK CA P1
> Add DomainComponent from RFC 2247

- README.md
Without the flag the human readable details would be output which fail once piped into `jq`.
> [trivial] added --json flag to readme examples

- starttls/imap.go
- starttls/starttls.go
This is a quick-and-dirty attempt to add STARTTLS support for the IMAP protocol ( see #120 ) inspired by a recent [blog post](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/InspectingTLSWithCertigo) by @Siebenmann. It definitely needs some review.
> Add support for IMAP STARTTLS

- .travis.yml
- lib/tls.go
Fix panic in explainCipher for TLS 1.3 ciphers. See #184.
> Fix panic in explainCipher for TLS 1.3 ciphers

- starttls/dialer.go
- starttls/starttls.go
This uses credentials, if present, from the URL.
This code is manually tested, but unfortunately there's not really a test suite setup for connecting to things.  I think that's a much bigger project than just adding this, so I'm punting on tests til later.
> HTTP Basic auth for `connect`

- lib/certs.go
- lib/verify.go
- tests/dump-csr-to-text.t
In reference to issue #177
Error when no valid certs are found when verifying instead of accessing oob
Warn when CSRs are found instead of silently ignoring them
> better error handling for csrs

- cli/cli.go
- cli/cli_test.go
- lib/certs.go
- lib/verify.go
- tests/dump-cert-chain-to-text.t
- tests/dump-leaf-to-not-verbose.t
- tests/dump-leaf-to-text.t
- tests/dump-name-constraints-to-text.t
- tests/dump-small-key-to-text.t
- tests/dump-spiffe-cert-to-text.t
Addresses issue #59 
Shows input format guessed by certigo as `Input Format` field in output
> print input format guessed by certigo

- cli/cli.go
- cli/cli_test.go
addresses #213
Only print input format when using dump. Never set this up for connect but inadvertently included print statement. Don't think functionality is useful for connect anyway so just removing the print
> no need to print input format when connecting to server

- .travis.yml
Previous key doesn't work any more and has failed the 1.12.0 release.
> Update OAuth token for GitHub Releases

- cli/cli.go
The latest released version is 1.12.1 @ f8835d9, however the version
string still reflects version 1.12.0, when run with:
```
$ certigo --version
```
Bump version string to lastest released version.
Signed-off-by: Nick Travers <n.e.travers@gmail.com>
> fix: bump version in cli.go

- go.sum
- starttls/starttls.go
> Avoid nil deref when using Postgres StartTLS

- .github/workflows/release.yaml
We had these on for Travis CI builds, so this should bring that
functionality back to GH Actions builds.
Based off of https://github.com/ghostunnel/ghostunnel/blob/f71137b46c6aab933c0cdb2e9797a95d30bfdb73/.github/workflows/release.yml
> Add automatic draft releases on tagged builds

- cli/cli.go
It's been a while since we released a new version, so seems like an appropriate time to bump the version.
> Bump version to 1.13.0

- lib/encoder.go
`certigo dump` on an Ed25519 cert before:
```
** CERTIFICATE 1 **
Input Format: PEM
Serial: 1
Valid: 2021-11-30 22:29 UTC to 2023-05-30 22:39 UTC
Signature: 16 (self-signed)
Subject Info:
CommonName: jdtw
Issuer Info:
CommonName: jdtw
Subject Key ID: FC:6B:63:10:A7:D5:D6:89:B0:74:DD:05:62:96:32:B4:E5:B9:CC:D4
Basic Constraints: CA:true, pathlen:0
Key Usage:
Cert Sign
CRL Sign
```
and after:
```
** CERTIFICATE 1 **
Input Format: PEM
Serial: 1
Valid: 2021-11-30 22:29 UTC to 2023-05-30 22:39 UTC
Signature: ED25519 (self-signed)
Subject Info:
CommonName: jdtw
Issuer Info:
CommonName: jdtw
Subject Key ID: FC:6B:63:10:A7:D5:D6:89:B0:74:DD:05:62:96:32:B4:E5:B9:CC:D4
Basic Constraints: CA:true, pathlen:0
Key Usage:
Cert Sign
CRL Sign
```
> Add the Ed25519 algo to the list of known algo names

- cli/cli.go
- lib/verify.go
This adds support to "certigo connect" to verify that the
server presented a certificate for a specific hostname or
SPIFFE ID. This name can now be unrelated to the hostname
to connect to and the Server Name Indication (SNI) to send
to the server during the TLS handshake.
Prior to this commit, the name expected in the certificate
could only be a hostname, specified either via --name (SNI)
or the hostname to connect to. SPIFFE IDs -- URLs with
"spiffe" as the scheme -- are not useful as hostnames or
SNIs. As a result, this commit adds a new --expected-name
switch to certigo connect. This override provides full
control over what name to expect in the server certificate
presented during the TLS handshake. For example, this name
can now be different from the hostname connected to and the
name …
> Add support for verifying server certs against SPIFFE IDs

- README.md
This is a follow-up to ba10cd1db70fd0292a77a67dcdfc4580b82cff61
where I forgot to update the usage in README. This commit adds
not only the new flag introduced in ba10cd1db70fd0292a77a67dcdfc4580b82cff61
but also the missing flags from older changes.
> Add missing flags in usage in README.md

- cli/cli.go
v1.14.0 has already been released. We'll do a point release to update the version string as reported by the `--version` flag.
> Bump version string to 1.14.1

- lib/ocsp.go
`certigo` displays the following misleading error when there are no OCSP servers in a chain:
```
Certificate has OCSP extension, but was unable to check status:
asn1: syntax error: sequence truncated
```
It tries to parse a zero-length OCSP response. This PR adds an upfront check to bypass OCSP if there aren't any servers in the chain.
> Don't check OCSP if there are no OCSP servers in the chain

- cli/cli_test.go
Go 1.17.7 changes the internal test cert and broke our tests[1]. Rather than taking a dependency on the internals of the http package, set the expected cert explicitly in the test servier.
[1] https://cs.opensource.google/go/go/+/90860e0c3110ac5898dfe8e0e0fafd0aea8d979a
> Set test certs explicitly

- cli/cli.go
`Format` isn't used in the connect flow (only dump). This leads to a panic:
```
❯ ./certigo connect google.com -l
panic: runtime error: slice bounds out of range [:1] with capacity 0
goroutine 1 [running]:
github.com/square/certigo/cli.Run({0xc000020090, 0x3, 0x3}, {0x14c3378, 0xc000010200})
/Users/jwood/Development/certigo/cli/cli.go:186 +0x187c
main.main()
/Users/jwood/Development/certigo/main.go:27 +0x89
```
> Remove use of the format list in the connect command

- cli/cli.go
Although 1.15.0 has been released, the --version flag is still reporting 1.14.1. I suggest a point release to update the version string, similar to #254.
> Bump version string to 1.15.1

- cli/cli_test.go
@bdd did an excellent writeup of the issue in https://github.com/square/certigo/issues/264. To fix this, stop relying on stable error messages between platforms and Go versions by performing a successful `certigo connect` in the test rather than a failed one.
I generated new ECDSA certificates for `localhost` using https://github.com/square/certstrap.
> Fix TestConnect on macOS

- README.md
As of Go 1.18, installing executables with `go get` is no longer available. So, I've changed to the `go install` command instead.
> Update go command to install certigo

- lib/ocsp.go
Fixes https://github.com/square/certigo/issues/280.
> Unconditionally add forward slash in OCSP GET requests

- go.mod
- go.sum
- lib/certs.go
Switch to using SSLMate's PKCS#12 library. The previous golang.org/x/crypto/pkcs12 library is frozen and not supported anymore. In particular, it doesn't support newer algorithms which are now seemingly the default in later versions of OpenSSL.
Here's an example of a PKCS#12 keystore (base64-encoded) generated with OpenSSL 3.0.2 which works with SSLMate's PKCS#12 library but does not work for me with the old Golang one:
```
MIIKbwIBAzCCCiUGCSqGSIb3DQEHAaCCChYEggoSMIIKDjCCBIIGCSqGSIb3DQEHBqCCBHMwggRv
AgEAMIIEaAYJKoZIhvcNAQcBMFcGCSqGSIb3DQEFDTBKMCkGCSqGSIb3DQEFDDAcBAivcQ20H0aH
OQICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEHzE5Z2ddnTWOiodBgkfB4CAggQAEam0
MCMMR+rwAkrERxrGBAeOWHSTZgclZLu99cJX1LrBlxWhmbdLKLcNL8R+ZyF82D5ztF1Jy4gNfW5+
+9cro0u3SaPKBQM85/dI9pnGIveEYjK4VP/HRyaEmGHL85X1oqY7dJpfdqW78ZI6 …
```
> Switch to using SSLMate's PKCS#12 library
